var data={
    "version":"1.0.0",
    "status":"SUCCESS",
    "errmsg":null,
    "obj":[
        {
            "totalSeller":20,
            "totalTrade":676,
            "totalMoney":"7248554",
            "categoryName":"酒店住宿"
        },
        {
            "totalSeller":183,
            "totalTrade":3826,
            "totalMoney":"36098286",
            "categoryName":"超市购物"
        },
        {
            "totalSeller":166,
            "totalTrade":9121,
            "totalMoney":"41558369",
            "categoryName":"美食餐饮"
        },
        {
            "totalSeller":62,
            "totalTrade":3638,
            "totalMoney":"26271095",
            "categoryName":"生活服务"
        },
        {
            "totalSeller":7,
            "totalTrade":86,
            "totalMoney":"264228",
            "categoryName":"休闲娱乐"
        },
        {
            "totalSeller":6,
            "totalTrade":79,
            "totalMoney":"594762",
            "categoryName":"丽人美发"
        }
    ],
    "total":6,
    "rate":null,
    "trade":null,
    "stats":null
}