var data={
    "version":"1.0.0",
    "status":"success",
    "errmsg":null,
    "obj":null,
    "total":0,
    "rate":null,
    "trade":[
        {
            "count":0,
            "total":476556.38,
            "localTransactionDate":null,
            "name":"观山湖区"
        },
        {
            "count":0,
            "total":475293.75,
            "localTransactionDate":null,
            "name":"花溪区"
        },
        {
            "count":0,
            "total":110215.61,
            "localTransactionDate":null,
            "name":"西秀区"
        },
        {
            "count":0,
            "total":106096.84,
            "localTransactionDate":null,
            "name":"云岩区"
        },
        {
            "count":0,
            "total":49663.5,
            "localTransactionDate":null,
            "name":"南明区"
        },
        {
            "count":0,
            "total":11051.66,
            "localTransactionDate":null,
            "name":"乌当区"
        },
        {
            "count":0,
            "total":1746.79,
            "localTransactionDate":null,
            "name":"白云区"
        }
    ],
    "stats":null
}