var data={
    "version":"1.0.0",
    "status":"SUCCESS",
    "errmsg":null,
    "obj":[
        {
            "totalSeller":11,
            "totalMoney":"91184",
            "totalTrade":53,
            "totalDate":0
        },
        {
            "totalSeller":8,
            "totalMoney":"44303",
            "totalTrade":14,
            "totalDate":1
        },
        {
            "totalSeller":2,
            "totalMoney":"51001",
            "totalTrade":3,
            "totalDate":2
        },
        {
            "totalSeller":2,
            "totalMoney":"1202",
            "totalTrade":3,
            "totalDate":3
        },
        {
            "totalSeller":2,
            "totalMoney":"9300",
            "totalTrade":2,
            "totalDate":4
        },
        {
            "totalSeller":1,
            "totalMoney":"1000",
            "totalTrade":1,
            "totalDate":5
        },
        {
            "totalSeller":4,
            "totalMoney":"8302",
            "totalTrade":11,
            "totalDate":6
        },
        {
            "totalSeller":18,
            "totalMoney":"341660",
            "totalTrade":274,
            "totalDate":7
        },
        {
            "totalSeller":36,
            "totalMoney":"1457005",
            "totalTrade":1194,
            "totalDate":8
        },
        {
            "totalSeller":86,
            "totalMoney":"3530949",
            "totalTrade":927,
            "totalDate":9
        },
        {
            "totalSeller":120,
            "totalMoney":"4189442",
            "totalTrade":669,
            "totalDate":10
        },
        {
            "totalSeller":169,
            "totalMoney":"9843601",
            "totalTrade":1417,
            "totalDate":11
        },
        {
            "totalSeller":150,
            "totalMoney":"15869327",
            "totalTrade":3977,
            "totalDate":12
        },
        {
            "totalSeller":166,
            "totalMoney":"15093552",
            "totalTrade":1636,
            "totalDate":13
        },
        {
            "totalSeller":191,
            "totalMoney":"13559853",
            "totalTrade":1016,
            "totalDate":14
        },
        {
            "totalSeller":189,
            "totalMoney":"4239416",
            "totalTrade":854,
            "totalDate":15
        },
        {
            "totalSeller":184,
            "totalMoney":"6087137",
            "totalTrade":791,
            "totalDate":16
        },
        {
            "totalSeller":142,
            "totalMoney":"10947806",
            "totalTrade":850,
            "totalDate":17
        },
        {
            "totalSeller":123,
            "totalMoney":"7432258",
            "totalTrade":1332,
            "totalDate":18
        },
        {
            "totalSeller":92,
            "totalMoney":"5549827",
            "totalTrade":1051,
            "totalDate":19
        },
        {
            "totalSeller":76,
            "totalMoney":"7027873",
            "totalTrade":694,
            "totalDate":20
        },
        {
            "totalSeller":52,
            "totalMoney":"3532278",
            "totalTrade":346,
            "totalDate":21
        },
        {
            "totalSeller":37,
            "totalMoney":"2914896",
            "totalTrade":194,
            "totalDate":22
        },
        {
            "totalSeller":16,
            "totalMoney":"212322",
            "totalTrade":119,
            "totalDate":23
        }
    ],
    "total":24,
    "rate":null,
    "trade":null,
    "stats":null
}